name: reusable-unity-build

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_call:
    inputs:
      project_path:
        required: true
        type: string
      unity_version:
        required: false
        type: string
        default: 2022.1.6f1
      target_platform:
        required: false
        type: string
        default: WebGL
    secrets:
      UNITY_LICENSE:
        required: true
      UNITY_EMAIL:
        required: true
      UNITY_PASSWORD:
        required: true

jobs:
  build:
    name: Build Unity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: ./
          key: Library-${{ github.sha }}
          restore-keys: Library-

      - name: build_unity_project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

        with:
          projectPath: ${{ inputs.project_path }}
          unityVersion: ${{ inputs.unity_version }}
          targetPlatform: ${{ inputs.target_platform }}

      - uses: actions/upload-artifact@v3
        with:
          name: duck_war_build
          path: build
