name: reusable-unity-build

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_call:
    inputs:
      unityVersion:
        required: false
        type: string
        default: 2022.1.6f1
      targetPlatform:
        required: false
        type: string
        default: WebGL
      projectPath:
        required: false
        type: string
        default: ./
    secrets:
      UNITY_LICENSE:
        required: true

jobs:
  build:
    name: Build Unity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: ./
          key: Library-${{ github.sha }}
          restore-keys: Library-

      - name: build_unity_project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ projectPath }}
          unityVersion: ${{ unityVersion }}
          targetPlatform: ${{ targetPlatform }}
