name: reusable-gke-deploy

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      deployment_tag:
        required: true
        type: string
      container_registry_name:
        required: false
        type: string
        default: ghcr.io
    secrets:
      workload_identity_provider:
        required: true
      gke_service_account:
        required: true
      gke_cluster:
        required: true
      gke_region:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ (github.ref_name == 'main' && github.event_name != 'pull_request') || (github.ref_name != 'main' && github.event_name != 'push' && github.event_name != 'pull_request') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account: ${{ secrets.gke_service_account }}

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v0.7.0
        with:
          cluster_name: ${{ secrets.gke_cluster }}
          location: ${{ secrets.gke_region }}

      # Deploy k8s objects to the GKE cluster
      - name: Deploy to GKE
        run: |-
          export IMAGE_NAME=${{ inputs.container_registry_name }}/${{ inputs.image_name }}:${{ inputs.deployment_tag }}
          echo $IMAGE_NAME
          sed -Ei "s|IMAGE_PLACEHOLDER|$IMAGE_NAME|g" k8s/deployment.yaml
          kubectl apply -k k8s/
